#+TITLE: OSSD Week 08
#+layout: post
#+categories: OSSD-class feelings guest-speaker emacs open-source-movement
#+liquid: enabled
#+feature_image: https://images.unsplash.com/photo-1514625796505-dba9ebaf5816?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1349&q=80
#+comments: true

This week, meeting Bill Reyner was awesome, and his talk helped broaden my mind a bit more. Also, I had to choose a potential project a for 'mid-sized' contribution, and I chose [[https://github.com/the-programmers-hangout/website][TPH's Website]].

*** Bill Reyner
To start with, meeting Bill Reyner of FactSet was awesome but also arose some questions that I may end up asking on Piazza soon. It was kind of a unique talk all around, since we see the super-secretive financial sector's company contributing to open source.

Before even talking about his talk, he's an emacs user, so that's already a plus in my books. He casually asked if I had written a major mode and I replied I hadn't but also referred to [[https://www.youtube.com/watch?v=w3krYEeqnyk][this kubernetes major mode video]]. I also realized at that point that there are a bunch of emacs packages and modules I could hunt as my contribution :smirk: But, it also didn't feel right per se since most of the issues tend to ask how something works or a request that requires extensive refactoring. There are some feature request which is extremely simple though, like 5 lines of code and viola.

Now then, during his actual talk, I was surprised that companies had to actively avoid GPL licensed projects. I didn't realize that using a GPL project would requires your entire project to also use GPL. However, I know of [[https://github.com/hetio/hetionet][Hetio Net]] which has a license attribute on a per node and per edge basis for sources with defined licenses, so this bring up a question I'll throw up later. Though, I'm kind of debating which licenses would be good for which kinds of projects. I like the fact that FactSet is steering towards OSS. It made a lot of sense to open source forks you no longer want to maintain and to open source resources you don't need as for competitive advantage. Also, you're not reinventing the wheel continuously. Sure a wheel is important, but the entire car's uniqueness ultimately doesn't depend on the wheels, so why not share how to make the wheel. Maybe someone will come along and improve the wheel a bit.

Reyner also mentioned how many engineers don't /know/ they're allowed to contribute to open source projects while working their corporate jobs (ie on the company's dime). I think that FactSet supporting open source contributions like that is extremely neat and I'd love to be in a similar environment in the future.

Reyner kind of killed my mood when he said there's no really clear way to make money with open source coding alone. I suppose creativity is the answer to all money woes... I've got high hopes for the lesson entailing the [[http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/index.html][The Cathedral and the Bazaar]] reading. I kind of get what it's getting hinting at, but looking over the requirements for week 09, I'll keep that to myself for now. Still, I'm kind of motivated to look at jobs from a different angle now.

*** Project
TPH is 'The Programmer Hangout'. Their website is a community project: made by the community for the community. Their main base is on Discord. I've actually joined the organization and worked on a different resource repository, but I decided to try my hand at web development as well. I like the idea of having community resources which is also open source so anyone can use them. I was thinking about tackling possibly [[https://github.com/the-programmers-hangout/website/issues/18][issue 18]]. It looks kind of tough, and honestly I haven't done anything similar to it before. However, I enjoy a good challenge, and I felt this issue was doable. Still, I may start off by giving some advice about languages first. I feel like that may be a good way to ease into the project and get a hang of how the different components interact with one another. I'm still kind of unsure if I want this to be /the/ project per se though, and I'm also not sure if the project will even get approved :sweat_smile:

*** Miscellaneous Questions
- How does multiple level licensing work? (eg the project is under a license and sub-directories are under various other licenses)
- Would a repository with git sub-modules vs a monolithic repository make a difference in the way to license?
