#+TITLE: OSSD Week 11
#+layout: post
#+categories: ossd-class wikipedia guest-speaker emacs articles analysis
#+liquid: enabled
#+feature_image: https://images.unsplash.com/photo-1514625796505-dba9ebaf5816?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1349&q=80
#+comments: true

This week was exciting. I made 2 edits to Wikipedia, learned some more UNIX commands, read an interesting article on open source BIOS coreboot, and met Kevin Fleming from Bloomberg LP.

*** Wikipedia
Wikipedia, my go to resource page, even when I don't mean to use it. It's insanely embedded in my daily life -- even when I don't plan on citing it, it's great for research as it acts as... well, and encyclopedia, as advertised I suppose. It has links to many references which are citable. The most interesting aspect to it however may be that it's heavily open source.

I'll admit, I was very intimated making a contribution to a resource used by people daily. My [[https://en.wikipedia.org/w/index.php?title=Klaus&diff=prev&oldid=926079309][first contribution]] was a super safe contribution: simply playing with internal hyperlinks. Wikipedia markup was sort of confusing to look at, but it turned out to be easy and I was able to add an internal hyperlink as well edit a broken one. On a side note, This was on a serious I had watched, but I came across it searching mythology -> beasts -> werewolves -> Klaus. I include that tidbit because for my next contribution I simply hit the random wikipedia article button :joy:. I came across Ric Brown's profile, a man I knew nothing about. But, I saw a red link and found that strange, and it turns out someone had tried to use Wikipedia's internal linking something that there was no entry for. So, I editted [[https://en.wikipedia.org/w/index.php?title=Ric_Brown&diff=prev&oldid=926082870][that]] to be an external link instead.

I also received a nice welcoming by a [[https://en.wikipedia.org/wiki/User:BrandonXLF][BrandonXLF]]. Seems like a nice man, and he seemed to want to help ease me into open source + Wikipedia. It also seems he's a person in the CS field... although I'm not sure what horrors go into getting specialized at Lua and Regex. Though, I definitely want to get better at regex. I'll throw in a small segment about my regex adventures this week below. Also, I may actually end up chatting Brandon up on his talk page later, since I was invited to, and because I'm still a little shaky on external resources on Wikipedia.

*** Regex
Hng. This has been annoying to learn because there seem to be different flavors and usage preferences. My first priority was to have my editor use =bash= configuration for my bash files. Its automatic mode list already has something for basic bash files, but my configuration has files such as =.bash_aliases= and =.bash_prompt= which don't get picked up. The thing is, as long as the file has the hook to the builtin =sh-mode=, it'll automatically try to pick up the mode based on the shebang, so all I had to do was hook =sh-mode=... easier said than done.

I looked into regex, for a while I had been using statements like =("\\.[rR]\\'" . R-mode)=, so I felt confident enough. seems the first =\= makes the string look at the basename, then the next =\= just escapes the =.=. A =[]= means something listed in the brackets, so the statement is equivalent to the combination of =("\\.r\\'" . R-mode)= and  =("\\.R\\'" . R-mode)=. Finally the =\'= seems to make the match happen to the end of a string. By this logic, I constructed the following statement:

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.bash_*\\'" . sh-mode))
#+END_SRC

This totally failed, and I wanted to play around with scripts right now, so I'm currently using:

#+BEGIN_SRC emacs-lisp
(shan/add-list-to-list 'auto-mode-alist '(("bash$" . sh-mode)
                                          ("bash_aliases$" . sh-mode)
                                          ("bash_exports$" . sh-mode)
                                          ("bash_functions$" . sh-mode)
                                          ("bash_logout$" . sh-mode)
                                          ("bash_prompt$" . sh-mode)
                                          ("zshrc$" . sh-mode)))
#+END_SRC
This is somewhat hard coded, but it works. What =shan/add-list-to-list= does is simply add a list to a list, because why would I want to add to a list 7 times when I could abstract it to 1 statement?

Something interesting I noted is when I opened a file like =.bash_history=, the mode was hooked, and I have no idea why or what the problem was now :thinking:. I would also like the mode hooked for when I do the linux commands assignment and also when I'm in specific directories (I made a fun little [[https://github.com/kkhan01/.myscripts][repository]] recently).

Anywho, I hope we have a small lesson on regex in class as well. It seems awfully useful. However, I dislike how it's super dependent on context. Wonder about the people who made =^= denote start of a string and exclude characters :pensive:. Also, I need to use it for my project contribution for the class anyways, but I think I can pick it up regardless :sweat_smile:

*** Open Source BIOS Coreboot
I first had to read [[https://cacm.acm.org/magazines/2019/10/239673-open-source-firmware/fulltext]["Open Firmware"]] by Jessie Frazelle per recommendation of the professor, and it was a pretty good recommendation since I don't know much about firmware. Highly suggest any onlookers also read it to gain some background information about what's what.

Next, the [[https://opensource.com/article/19/11/coreboot-system76-laptops?utm_campaign=intrel]["System76 introduces laptops with open source BIOS coreboot"]] article is what we'll make sense of. Coincidentally, I was in the market for a new laptop as well. I was talking to my friend about Thinkpads (since they're sexy beasts) and how the Carbon X1 is so slick, but nevertheless, its price is kind of insane. And so the Dell XPS 13 is brought up, and he says "those are pretty much the only ones you can libreboot". I was confused, what was librebooting? In my small journey, I found [[https://libreboot.org/][https://libreboot.org/]] to be enlightening. Seems great, this is a good thing that was obviously entailing the advent of open source operating systems. Looking around though, many people describe the process of librebooting as 'harrowing'. So, this is where System76 comes into play. It'll be shipping the open firmware on two of their laptop models, so there's no hassle for the user :tada:.

The message is quite obvious: if software is open source, why shouldn't the software of the hardware also be open source? I like the idea of open source. Sometimes booting up a new distro or my stable distro takes a bit, and I'd like to see what's happening behind the scenes. Still... System76 is out of my budget :weary:

*** Bloomberg
Kevin Fleming came by to talk about Bloomberg's involvement in open source. Honestly, it sounded incredible.

They have events in which they splurge money to get maintainers and developers to meet, and apparently any ol' developer is allowed to attend these conferences. Seems like they do a hackerspace but focused on open source, which is pretty cool. Combining the open source movement with the philanthropy departments seems like a no brainer :eyes:

Also, they seem to be entangled with many open source projects such as Jupyter and Apache. Seems they've contributed tot he extent they're in on the roadmap and reviewing changes. A question that popped in class was if Bloomberg lost interest in a project (due to gain of interest in another), would they just abandon it? Wouldn't that mess up its hierarchical structure? I think not. These projects were fully functional alone and Bloomberg just sped up its advancement. I feel like these advancements would have happened anyways, but in any case, I doubt they will loose interest in them.

And now for the inevitable: FactSet vs Bloomberg. We started to discuss this in class -- both are in the financial sector. That means they're out of profit, not the good of the community like FSF per se. I mean, they're not inhumane, but they aren't going to start contributing to libraries just for the heck of it. A contribution to an open source project likely indicates they use that technology, or have a technology that does. Often they may contribute so they don't have to maintain a fork themselves, or because it doesn't give them a comparative advantage, so might as well share and reap the benefits of open source development.

My biggest gripe is that both speakers seemed to indicate contributing to open source required some sort of agenda. A developer doesn't seem to be able to make money based only writing and contributing to open source :pensive:. The professor still has me hoping someone from a big open source epitome company model like RedHat or Mozilla will drop by. I think I'd like to pursue a career in open source eventually, but I still need to look out for #1: me :relaxed:

*** Honorable OSS Project Mention
Not much progress here honestly. Actually, I'm stuck at regex problem. I need to determine the 404 page served up, and examples seem to use regex, so I'm working on decoding the examples so I can repurpose the logic to fit my needs. Regex strikes once again.

*** End of Post
Seems I'm almost done setting up a sync between the OSSD blog and my personal blog. Just need to work out a few more kinks and I should be posting on both quite nicely :shipit:

Cheers
