#+TITLE: Blogging
#+layout: post
#+categories: blogging gh-pages jekyll netlify tech
#+liquid: enabled
#+feature_image: https://picsum.photos/1300/400?image=989

Choosing how your blog will live, either for the first time or the twentieth time, can be overwhelming. Luckily we've got posts like this one: users sharing their experience to help you!

As a note: My blog currently lives by means of Jekyll and Netlify. The code is available [[https://github.com/kkhan01/alembic-kit][here]]. This post isn't sponsored by anyone (although I wish it was... :wink:). These are just awesome technologies I use(d) and felt like sharing.

*** My goal
To start with: I wanted to be able to micro-manage aspects of the sites if I chose to but also have a streamline workflow as well. That may be confusing, which is totally okay because it's also somewhat contradictory. To put it more simple, I wanted a setup whose ins and outs I knew well enough to customize, but I also wouldn't have to put in too much work everytime I wanted to post.

*** How I Got Started
My web story begins in high school. I was at a hackathon, and I received a voucher for a free domain for a year. Freebies like that are a great way to reel people into the world of CD. If I could go back and do it again, I would've probably only changed the name of the domain. But alas, I digress. As a high school student, I wanted my website to be /free/, because which highschooler would want to pay for hosting after getting a free domain? So the goal is now something maintainable and free as well :shipit: I was already using [[https://github.com][GitHub]] at the time for schoolwork, so [[https://pages.github.com/][GitHub Pages]] appealed to me. All you need is a free Github account, and you just push to a repository as you would push normal code and viola: you've got a site up and running. In layman's terms, you save the source code to your website in a folder which is saved under your Github account (online).

*** My Journey
I've tried out a lot of technologies for a blog, all my attempts are archived [[https://github.com/kkhan01/kkhan01.github.io][here]] in the commits. [ /Get ready for a bunch of links, since this is a journey/ ] I've gone from [[https://jekyllrb.com/][Jekyll]] to [[https://github.com/Frozen-Flask/Frozen-Flask][Frozen Flask]] to [[http://harpjs.com/][Harp]] with a bunch of switching back and forth with slight differences like using [[https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll][Clean Blog]] theme with [[https://jekyllrb.com/][Jekyll]] vs trying [[https://github.com/kkhan01/first-jekyll-theme][my own theme]] (totally abandoned, might pick it up as a learning exercise again :pensive:) vs [[https://github.com/daviddarnes/alembic][alembic kit]]. I've also tried a few more other technologies like [[https://www.gatsbyjs.org/][Gatsby]], [[https://gohugo.io/][Hugo]], etcetera etcetera. I settled on [[https://github.com/Frozen-Flask/Frozen-Flask][Frozen Flask]] for probably the longest time, since I was familiar with [[https://github.com/pallets/flask][Flask]]. It was also very fun setting it up from scratch. But [[https://jekyllrb.com/][Jekyll]] proved to be better choice in the end. Maybe I'll talk about my experience with each of those technologies one day.

*** El Fin 終わり
I know this post probably raised a lot of questions and has a lot of different content just thrown in and abruptly stopped, but such is the bittersweetness of a short and sweet post. I was advised to try and keep a [[https://en.wikipedia.org/wiki/Microblogging][microblog]] to calm need for perfection (which would've resulted in no posts :scream:), but I decided to do a variation. I'll definitely write more about this though, so look forward to it! :+1:
