#+TITLE: Blogging
#+LAYOUT: post
#+CATEGORIES: blogging jekyll netlify gh-pages tech
#+feature_image: https://images.unsplash.com/photo-1514625796505-dba9ebaf5816?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1349&q=80

Choosing how your blog will live, either for the first time or the twentieth time, can be overwhelming. Luckily we've got posts like this one: users sharing their experience to help you!

As a note: My blog currently lives by means of Jekyll and Netlify. The code is available [[https://github.com/kkhan01/alembic-kit][here]]. This post isn't sponsored by anyone (although I wish it was... :wink:). These are just awesome technologies I use(d) and felt like sharing.

*** My goal
To start with: I wanted to be able to micro-manage aspects of the sites if I chose to but also have a streamline workflow as well. That may be confusing, which is totally okay because it's also somewhat contradictory. To put it more simple, I wanted a setup whose ins and outs I knew well enough to customize, but I also wouldn't have to put in too much work everytime I wanted to post.

*** How I Got Started
I suppose my first start was in high school. I was at a hackathon, and I received a voucher for a domain for a year. Freebies like that are a great way to reel people into the world of cs. If I could go back and do it again, I would've probably only changed the name of the domain. But alas, I digress. As a high school student, I wanted my website to be /free/, because which highschooler would want to pay for hosting after getting a free domain? So the goal is now something maintainable and free as well :shipit: I was already using [[https://github.com][GitHub]] at the time for schoolwork, so [[https://pages.github.com/][GitHub Pages]] appealed to me. All you need is a free Github account, and you just push to a repository as you would push normal code and viola, you've got a site up and running. In layman's terms, you save the source code to your website in a folder which is saved under your Github account.

*** My Journey
I've tried out a lot of technologies for a blog, all my attempts are archived [[https://github.com/kkhan01/kkhan01.github.io][here]] in the commits. I've gone from Jekyll to Frozen Flask toHarp with a bunch of switching back and forth and other technologies. I settled on Frozen Flask for probably the longest time, since I was familiar with Flask. But Jekyll proved to be better choice in the end. Maybe I'll talk about my experience with each of those technologies one day.

*** El Fin 終わり
I know this post probably raised a lot of questions and has a lot of different content just thrown in and abruptly stopped, but such is the bittersweetness of a short and sweet post. I'll definitely write more about this though, so look forward to it!
